components:
  schemas:
    NetCDF:
      properties:
        dimensions:
          description: The dimensions of the NetCDF file.
          properties:
            location:
              properties:
                size:
                  description: The size of the location dimension.
                  example: 0
                  type: integer
              type: object
          type: object
        format:
          description: The format of the NetCDF file.
          example: NETCDF4
          type: string
        variables:
          description: The variables of the NetCDF file.
          items:
            properties:
              section_capacity:
                properties:
                  attributes:
                    description: The attributes of the section_capacity variable.
                    properties:
                      example: {}
                    type: object
                  data:
                    description: The data of the section_capacity variable.
                    items: {}
                    type: array
                  dimensions:
                    description: The dimensions of the section_capacity variable.
                    items:
                      example:
                      - location
                      type: string
                    type: array
                  dtype:
                    description: The data type of the section_capacity variable.
                    example: float64
                    type: string
                type: object
              section_modules_cost:
                properties:
                  attributes:
                    description: The attributes of the section_modules_cost variable.
                    properties:
                      example:
                        Currency: EUR
                    type: object
                  data:
                    description: The data of the section_modules_cost variable.
                    items: {}
                    type: array
                  dimensions:
                    description: The dimensions of the section_modules_cost variable.
                    items:
                      example:
                      - location
                      type: string
                    type: array
                  dtype:
                    description: The data type of the section_modules_cost variable.
                    example: float64
                    type: string
                type: object
              section_yearly_system_generation:
                properties:
                  attributes:
                    description: The attributes of the section_yearly_system_generation
                      variable.
                    properties:
                      example: {}
                    type: object
                  data:
                    description: The data of the section_yearly_system_generation
                      variable.
                    items: {}
                    type: array
                  dimensions:
                    description: The dimensions of the section_yearly_system_generation
                      variable.
                    items:
                      example:
                      - location
                      type: string
                    type: array
                  dtype:
                    description: The data type of the section_yearly_system_generation
                      variable.
                    example: float64
                    type: string
                type: object
          type: array
      type: object
info:
  title: NetCDF File Schema
  version: 1.0.0
openapi: 3.0.0
